config/routes.rb
Folktell::Application.routes.draw do
  resources :beers

  devise_for :users
  root "pages#home"
  get "about" => "pages#about"

  

end

app/models/beer.rb
class Beer < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many :beers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  
  # GET /beers
  # GET /beers.json
  def index
    @beers = Beer.all
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
  end

  # GET /beers/new
  def new
    @beer = current_user.beers.build
  end

  # GET /beers/1/edit
  def edit
  end

  # POST /beers
  # POST /beers.json
  def create
    @beer = current_user.beers.build(beer_params)

    respond_to do |format|
      if @beer.save
        format.html { redirect_to @beer, notice: 'Beer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @beer }
      else
        format.html { render action: 'new' }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beers/1
  # PATCH/PUT /beers/1.json
  def update
    respond_to do |format|
      if @beer.update(beer_params)
        format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    @beer.destroy
    respond_to do |format|
      format.html { redirect_to beers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer
      @beer = Beer.find(params[:id])
    end

    def correct_user
      @beer = current_user.beers.find_by(id: params[:id])
      redirect_to beers_path, notice: "Not authorized to edit this Beer!" if @beer.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_params
      params.require(:beer).permit(:description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/beers/_form.html.erb
<%= form_for(@beer) do |f| %>
  <% if @beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
      <% @beer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/beers/edit.html.erb
<div class="panel panel-default">
	<div class="panel-heading"><h1>Editing beer</h1></div>
	<div class="panel-body">

<%= render 'form' %>

	</div>

	<div class="panel-footer"><%= link_to 'Show', @beer %> |
		<%= link_to 'Back', beers_path %>
	</div>
</div>

app/views/beers/index.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
  		<h1>Listing beers</h1></div>
	<div class="panel-body">

		<table>
		  <thead>
		    <tr>
		      <th>When</th>
		      <th>Description</th>
		      <th>User email</th>
		      <th>Options</th>
		    </tr>
		  </thead>

		  <tbody>
		    <% @beers.each do |beer| %>
		      <tr>
		        <td><%= beer.created_at.strftime("%B %d, %Y") %></td>
		        <td><%= beer.description %></td>
		        <td><%= beer.user.email if beer.user %></td>
		        <td><%= link_to 'Show', beer %>
		        	<% if beer.user == current_user %> | 
		        	<%= link_to 'Edit', edit_beer_path(beer) %> | 
		            <%= link_to 'Destroy', beer, method: :delete, data: { confirm: 'Are you sure?' } %>
		            <% end %>
		        </td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>

		<br>
	</div>

	<div class="panel-footer">
		<% if user_signed_in? %>
			<%= link_to 'New Beer', new_beer_path %>
		<% end %>
	</div>

</div>

app/views/beers/new.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h1>New beer</h1>
	</div>
	<div class="panel-body">

		<%= render 'form' %>
		
	</div>

	<div class="panel-footer">
		<%= link_to 'Back', beers_path %>
	</div>
</div>

app/views/beers/show.html.erb
<div class="panel panel-default">
	<div class="panel-body">

		<p id="notice"><%= notice %></p>

		<p>
		  <strong>Description:</strong>
		  <%= @beer.description %>
		</p>
	</div>
	<div class="panel-footer">
		<% if @beer.user == current_user %>
			<%= link_to 'Edit', edit_beer_path(@beer) %> 
		<% end %>
		<%= link_to 'Back', beers_path %>
	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "RoyBeers", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Account", edit_user_registration_path %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RoyBeers</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
	<%= render 'layouts/header' %>

	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
	<h1>About RoyBeers</h1>
	<p>Just playing around with rails and heroku</p>
</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Follow the beers</h1>
	<p>Preserving the IOU trail with a small rails project</p>
	
	<% if user_signed_in? %>
		<p>
			Yo what's up?
		</p>
	<% else %>
		<p>
			<%= link_to "Sign in", new_user_session_path, class: "btn btn-default btn-lg" %>
			<%= link_to "Get started", new_user_registration_path, class: "btn btn-primary btn-lg" %>
		</p>
	<% end %>
</div>